# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.FileField(upload_to=b'')),
                ('groupName', models.CharField(max_length=30, verbose_name='\u041a\u043e\u043b\u043b\u0435\u043a\u0442\u0438\u0432')),
                ('city', models.CharField(max_length=30, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430,\u0433\u043e\u0440\u043e\u0434')),
                ('director', models.CharField(max_length=30, verbose_name='\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
                ('teacher', models.CharField(max_length=30, verbose_name='\u041f\u0435\u0434\u0430\u0433\u043e\u0433/\u0445\u043e\u0440\u0435\u043e\u0433\u0440\u0430\u0444')),
                ('phoneNumber', models.CharField(max_length=30, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('institution', models.CharField(max_length=30, verbose_name='\u0423\u0447\u0440\u0435\u0436\u0434\u0435\u043d\u0438\u0435')),
                ('addressInstitution', models.CharField(max_length=30, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0443\u0447\u0440\u0435\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('postalAddress', models.CharField(max_length=30, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0430\u0434\u0440\u0435\u0441')),
                ('site', models.CharField(max_length=30, verbose_name='\u0421\u0430\u0439\u0442')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('date_change_admin', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0430 \u0438\u043b\u0438 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f \u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u043c')),
                ('date_change_dir', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u043c')),
                ('payment', models.FloatField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('moderacia', '\u041d\u0430 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438'), ('warn', '\u0412\u043d\u0435\u0441\u0438\u0442\u0435 \u0438\u0441\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f'), ('ok', '\u0417\u0430\u044f\u0432\u043a\u0430 \u043f\u0440\u0438\u043d\u044f\u0442\u0430')], max_length=100, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('status_comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('date_change_admin', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0430 \u0438\u043b\u0438 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f \u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u043c')),
                ('date_change_dir', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u043c')),
                ('payment', models.FloatField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u0442\u0430')),
                ('tour_form', models.CharField(choices=[(b'EveningCheb', '\u0412\u0435\u0447\u0435\u0440\u043d\u0438\u0435 \u0427\u0435\u0431\u043e\u043a\u0441\u0430\u0440\u044b'), (b'obzorCheb', '\u041e\u0431\u0437\u043e\u0440\u043d\u0430\u044f \u044d\u043a\u0441\u043a\u0443\u0440\u0441\u0438\u044f \u043f\u043e \u0433. \u0427\u0435\u0431\u043e\u043a\u0441\u0430\u0440\u044b')], max_length=100, verbose_name='\u0424\u043e\u0440\u043c\u0430 \u044d\u043a\u0441\u043a\u0443\u0440\u0441\u0438\u0438')),
                ('date_departure', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u0431\u044b\u0442\u0438\u044f')),
                ('time_departure', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u0431\u044b\u0442\u0438\u044f')),
                ('quantity_total', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u0431\u0449\u0435\u0435')),
                ('quantity_adult', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u0437\u0440\u043e\u0441\u043b\u044b\u0445')),
                ('quantity_member', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432')),
            ],
            options={
                'verbose_name': '\u044d\u043a\u0441\u043a\u0443\u0440\u0441\u0438\u044f',
                'verbose_name_plural': '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u044d\u043a\u0441\u043a\u0443\u0440\u0441\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('moderacia', '\u041d\u0430 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438'), ('warn', '\u0412\u043d\u0435\u0441\u0438\u0442\u0435 \u0438\u0441\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f'), ('ok', '\u0417\u0430\u044f\u0432\u043a\u0430 \u043f\u0440\u0438\u043d\u044f\u0442\u0430')], max_length=100, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('status_comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('date_change_admin', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0430 \u0438\u043b\u0438 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f \u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u043c')),
                ('date_change_dir', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u043c')),
                ('age_group', models.CharField(choices=[('0-7', '\u0434\u043e 7 \u043b\u0435\u0442'), ('8-10', '8-10 \u043b\u0435\u0442'), ('11-14', '11-14 \u043b\u0435\u0442'), ('15-18', '15-18 \u043b\u0435\u0442'), ('18-25', '18-25 \u043b\u0435\u0442')], max_length=10, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442\u043d\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430')),
                ('first_name', models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=30, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('age', models.IntegerField(verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('gender', models.CharField(choices=[('male', '\u041c'), ('female', '\u0416')], max_length=10, verbose_name='\u041f\u043e\u043b')),
                ('scan_passport', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0421\u043a\u0430\u043d \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430, \u0443\u0434\u043e\u0441\u0442\u043e\u0432\u0435\u0440\u044f\u044e\u0449\u0435\u0433\u043e \u043b\u0438\u0447\u043d\u043e\u0441\u0442\u044c')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a',
                'verbose_name_plural': '\u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=30)),
                ('news', models.TextField()),
            ],
            options={
                'verbose_name': '\u043d\u043e\u0432\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u043d\u043e\u0432\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('moderacia', '\u041d\u0430 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438'), ('warn', '\u0412\u043d\u0435\u0441\u0438\u0442\u0435 \u0438\u0441\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f'), ('ok', '\u0417\u0430\u044f\u0432\u043a\u0430 \u043f\u0440\u0438\u043d\u044f\u0442\u0430')], max_length=100, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('status_comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('date_change_admin', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0430 \u0438\u043b\u0438 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f \u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u043c')),
                ('date_change_dir', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u043c')),
                ('payment', models.FloatField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u0442\u0430')),
                ('category', models.CharField(choices=[(b'adults', b'\xd0\xa0\xd0\xb0\xd0\xb4\xd1\x83\xd0\xb3\xd0\xb0-\xd1\x82\xd0\xb0\xd0\xbd\xd1\x86\xd0\xb0'), (b'kids', b'\xd0\xa0\xd0\xb0\xd0\xb4\xd1\x83\xd0\xb3\xd0\xb0-\xd1\x82\xd0\xb0\xd0\xbd\xd1\x86\xd0\xb0 KIDS')], max_length=30, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('nomination', models.CharField(choices=[(b'estrada', '\u042d\u0441\u0442\u0440\u0430\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'narod', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'narod_style', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0441\u0442\u0438\u043b\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'sovremen_svobod', '\u0421\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446 (\u0441\u0432\u043e\u0431\u043e\u0434\u043d\u0430\u044f \u043f\u043b\u0430\u0441\u0442\u0438\u043a\u0430)'), (b'sovremen_ulica', '\u0421\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446 (\u0443\u043b\u0438\u0447\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446)'), (b'classic', '\u041a\u043b\u0430\u0441\u0441\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'narod+_narod_style', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446, \u043d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0441\u0442\u0438\u043b\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'suget-igrovoi', '\u0421\u044e\u0436\u0435\u0442\u043d\u043e-\u0438\u0433\u0440\u043e\u0432\u043e\u0439 \u0442\u0430\u043d\u0435\u0446 ')], max_length=30, verbose_name='\u041d\u043e\u043c\u0438\u043d\u0430\u0446\u0438\u044f')),
                ('age_group', models.CharField(choices=[('0-7', '\u0434\u043e 7 \u043b\u0435\u0442'), ('8-10', '8-10 \u043b\u0435\u0442'), ('11-14', '11-14 \u043b\u0435\u0442'), ('15-18', '15-18 \u043b\u0435\u0442'), ('18-25', '18-25 \u043b\u0435\u0442')], max_length=10, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442\u043d\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430')),
                ('form_of_execution', models.CharField(choices=[('solo', '\u0441\u043e\u043b\u043e'), ('duet', '\u0434\u0443\u044d\u0442'), ('ensamble', '\u0430\u043d\u0441\u0430\u043c\u0431\u043b\u044c')], max_length=10, verbose_name='\u0424\u043e\u0440\u043c\u0430 \u0438\u0441\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f')),
                ('composition_1', models.CharField(max_length=30, verbose_name='\u041a\u043e\u043c\u043f\u043e\u0437\u0438\u0446\u0438\u044f')),
                ('description_comp', models.TextField(blank=True, max_length=2000, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043a \u0442\u0430\u043d\u0446\u0443')),
                ('count_member_1', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432')),
                ('composition_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u041a\u043e\u043c\u043f\u043e\u0437\u0438\u0446\u0438\u044f \u21162')),
                ('count_member_2', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432')),
                ('list_member', models.ManyToManyField(to='app.Member', verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432')),
            ],
            options={
                'verbose_name': '\u0437\u0430\u044f\u0432\u043a\u0430 \u043d\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u0435',
                'verbose_name_plural': '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='Place_arrival_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place_departure_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Residing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('moderacia', '\u041d\u0430 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438'), ('warn', '\u0412\u043d\u0435\u0441\u0438\u0442\u0435 \u0438\u0441\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f'), ('ok', '\u0417\u0430\u044f\u0432\u043a\u0430 \u043f\u0440\u0438\u043d\u044f\u0442\u0430')], max_length=100, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('status_comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('date_change_admin', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0430 \u0438\u043b\u0438 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f \u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u043c')),
                ('date_change_dir', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u043c')),
                ('payment', models.FloatField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u0442\u0430')),
                ('place_of_residing', models.CharField(choices=[(b'Chgpu', '\u0421\u0430\u043d\u0430\u0442\u043e\u0440\u0438\u0439 \u043f\u0440\u043e\u0444\u0438\u043b\u0430\u043a\u0442\u043e\u0440\u0438\u0439 \u0427\u0413\u041f\u0423 \u0438\u043c. \u0418.\u042f. \u042f\u043a\u043e\u0432\u043b\u0435\u0432\u0430 "\u041c\u0435\u0447\u0442\u0430"'), (b'Gemchugina', '\u041e\u0437\u0434\u043e\u0440\u043e\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0441 "\u0416\u0435\u043c\u0447\u0443\u0436\u0438\u043d\u0430 \u0427\u0443\u0432\u0430\u0448\u0438\u0438"')], max_length=30, verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u044f')),
                ('quantity_total', models.IntegerField(verbose_name='\u041e\u0431\u0449\u0435\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u044e\u0449\u0438\u0445')),
                ('quantity_adult_male', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u0437\u0440\u043e\u0441\u043b\u044b\u0445 \u041c')),
                ('quantity_adult_female', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u0437\u0440\u043e\u0441\u043b\u044b\u0445 \u0416')),
                ('quantity_member_male', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432 \u041c')),
                ('quantity_member_female', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432 \u0416')),
                ('date_arrival', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0435\u0437\u0434\u0430')),
                ('time_arrival', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u0435\u0437\u0434\u0430')),
                ('date_departure', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u044a\u0435\u0437\u0434\u0430')),
                ('time_departure', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u044a\u0435\u0437\u0434\u0430')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='Subgroup_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('moderacia', '\u041d\u0430 \u043c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u0438'), ('warn', '\u0412\u043d\u0435\u0441\u0438\u0442\u0435 \u0438\u0441\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f'), ('ok', '\u0417\u0430\u044f\u0432\u043a\u0430 \u043f\u0440\u0438\u043d\u044f\u0442\u0430')], max_length=100, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('status_comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('date_change_admin', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0430 \u0438\u043b\u0438 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f \u043c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440\u043e\u043c')),
                ('date_change_dir', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u043c')),
                ('payment', models.FloatField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u0442\u0430')),
                ('date_departure', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u0431\u044b\u0442\u0438\u044f')),
                ('time_departure', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u0431\u044b\u0442\u0438\u044f')),
                ('quantity_total', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u0431\u0449\u0435\u0435')),
                ('quantity_adult', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u0437\u0440\u043e\u0441\u043b\u044b\u0445')),
                ('quantity_member', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432')),
                ('place_arrival', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_arrival', to='app.Place_departure_choices', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f')),
                ('place_departure', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_departure', to='app.Place_departure_choices', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043e\u0442\u0431\u044b\u0442\u0438\u044f')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0442\u0440\u0430\u043d\u0441\u0444\u0435\u0440',
                'verbose_name_plural': '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0442\u0440\u0430\u043d\u0441\u0444\u0435\u0440',
            },
        ),
        migrations.AddField(
            model_name='participation',
            name='subgroup',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subgroup_choices', verbose_name='\u041f\u043e\u0434\u0433\u0440\u0443\u043f\u043f\u0430 \u043a\u043e\u043b\u043b\u0435\u043a\u0442\u0438\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excursion',
            name='place_arrival',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_place_arrival', to='app.Place_departure_choices', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='place_departure',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_place_departure', to='app.Place_departure_choices', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043e\u0442\u0431\u044b\u0442\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
