# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_director_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='payment',
            field=models.FloatField(blank=True, null=True, verbose_name='\u041f\u043b\u0430\u0442\u0430'),
        ),
    ]
