# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_director_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.CharField(default='\u0420\u043e\u0441\u0441\u0438\u044f', max_length=30, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='director',
            name='city',
            field=models.CharField(max_length=30, verbose_name='\u0413\u043e\u0440\u043e\u0434 \u043d/\u043f.'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='place_arrival',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_place_arrival', to='app.Place_departure_choices', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='place_departure',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_place_departure', to='app.Place_departure_choices', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043e\u0442\u0431\u044b\u0442\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='category',
            field=models.CharField(choices=[('adults', '\u0420\u0430\u0434\u0443\u0433\u0430-\u0442\u0430\u043d\u0446\u0430'), ('kids', '\u0420\u0430\u0434\u0443\u0433\u0430-\u0442\u0430\u043d\u0446\u0430 KIDS'), ('spec', '\u0421\u043f\u0435\u0446. \u043d\u043e\u043c\u0438\u043d\u0430\u0446\u0438\u044f')], max_length=30, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='form_of_execution',
            field=models.CharField(choices=[('solo', '\u0441\u043e\u043b\u043e'), ('duet', '\u043c\u0430\u043b\u0430\u044f \u0444\u043e\u0440\u043c\u0430'), ('ensamble', '\u0430\u043d\u0441\u0430\u043c\u0431\u043b\u044c')], max_length=10, verbose_name='\u0424\u043e\u0440\u043c\u0430 \u0438\u0441\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='nomination',
            field=models.CharField(choices=[(b'estrada', '\u042d\u0441\u0442\u0440\u0430\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'narod', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'narod_style', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0441\u0442\u0438\u043b\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'sovremen_svobod', '\u0421\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446 (\u0441\u0432\u043e\u0431\u043e\u0434\u043d\u0430\u044f \u043f\u043b\u0430\u0441\u0442\u0438\u043a\u0430)'), (b'sovremen_ulica', '\u0421\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446 (\u0443\u043b\u0438\u0447\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446)'), (b'classic', '\u041a\u043b\u0430\u0441\u0441\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'narod+_narod_style', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446, \u043d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0441\u0442\u0438\u043b\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'suget-igrovoi', '\u0421\u044e\u0436\u0435\u0442\u043d\u043e-\u0438\u0433\u0440\u043e\u0432\u043e\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'spec', '\u0412\u0435\u043b\u0438\u043a\u043e\u0439 \u043f\u043e\u0431\u0435\u0434\u0435 \u043f\u043e\u0441\u0432\u044f\u0449\u0430\u0435\u0442\u0441\u044f')], max_length=30, verbose_name='\u041d\u043e\u043c\u0438\u043d\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='place_arrival',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_arrival', to='app.Place_departure_choices', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='place_departure',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_departure', to='app.Place_departure_choices', verbose_name='\u041c\u0435\u0441\u0442\u043e \u043e\u0442\u0431\u044b\u0442\u0438\u044f'),
        ),
    ]
