# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160208_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='postalAddress',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
    ]
