# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160209_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_title', models.CharField(max_length=30)),
                ('reg', models.TextField()),
            ],
            options={
                'verbose_name': '\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='age_group',
            field=models.CharField(choices=[('0-7', '\u0434\u043e 7 \u043b\u0435\u0442'), ('8-10', '8-10 \u043b\u0435\u0442'), ('11-14', '11-14 \u043b\u0435\u0442'), ('15-18', '15-18 \u043b\u0435\u0442'), ('18-25', '18-25 \u043b\u0435\u0442'), ('hybrid', '\u0441\u043c\u0435\u0448\u0430\u043d\u043d\u0430\u044f')], max_length=10, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442\u043d\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='age_group',
            field=models.CharField(choices=[('0-7', '\u0434\u043e 7 \u043b\u0435\u0442'), ('8-10', '8-10 \u043b\u0435\u0442'), ('11-14', '11-14 \u043b\u0435\u0442'), ('15-18', '15-18 \u043b\u0435\u0442'), ('18-25', '18-25 \u043b\u0435\u0442'), ('hybrid', '\u0441\u043c\u0435\u0448\u0430\u043d\u043d\u0430\u044f')], max_length=10, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442\u043d\u0430\u044f \u0433\u0440\u0443\u043f\u043f\u0430'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='nomination',
            field=models.CharField(choices=[(b'estrada', '\u042d\u0441\u0442\u0440\u0430\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'narod', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'narod_style', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0441\u0442\u0438\u043b\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'sovremen_svobod', '\u0421\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446 (\u0441\u0432\u043e\u0431\u043e\u0434\u043d\u0430\u044f \u043f\u043b\u0430\u0441\u0442\u0438\u043a\u0430)'), (b'sovremen_ulica', '\u0421\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446 (\u0443\u043b\u0438\u0447\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446)'), (b'narod+_narod_style', '\u041d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446, \u043d\u0430\u0440\u043e\u0434\u043d\u044b\u0439 \u0441\u0442\u0438\u043b\u0438\u0437\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'suget-igrovoi', '\u0421\u044e\u0436\u0435\u0442\u043d\u043e-\u0438\u0433\u0440\u043e\u0432\u043e\u0439 \u0442\u0430\u043d\u0435\u0446'), (b'spec', '\u0412\u0435\u043b\u0438\u043a\u043e\u0439 \u043f\u043e\u0431\u0435\u0434\u0435 \u043f\u043e\u0441\u0432\u044f\u0449\u0430\u0435\u0442\u0441\u044f')], max_length=30, verbose_name='\u041d\u043e\u043c\u0438\u043d\u0430\u0446\u0438\u044f'),
        ),
    ]
