# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160221_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reglaments',
            options={'verbose_name': '\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u044f'},
        ),
        migrations.AlterField(
            model_name='director',
            name='addressInstitution',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0443\u0447\u0440\u0435\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='director',
            name='institution',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0423\u0447\u0440\u0435\u0436\u0434\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='director',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='director',
            name='site',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='director',
            name='teacher',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u041f\u0435\u0434\u0430\u0433\u043e\u0433/\u0445\u043e\u0440\u0435\u043e\u0433\u0440\u0430\u0444'),
        ),
    ]
