# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160303_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='foto',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
