# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_news_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
    ]
