# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160309_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='file_music',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b \u043a\u043e\u043c\u043f\u043e\u0437\u0438\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='residing',
            name='place_of_residing',
            field=models.CharField(choices=[(b'dush4', '\u0421\u0414\u042e\u0421\u0428\u041e\u0420 \u21164'), (b'dush3', '\u0421\u0414\u042e\u0421\u0428\u041e\u0420 \u21163'), (b'admiral', '\u0413\u043e\u0441\u0442\u0438\u043d\u0438\u0446\u0430 \xab\u0410\u0434\u043c\u0438\u0440\u0430\u043b\xbb'), (b'salampi', 'C\u0430\u043d\u0430\u0442\u043e\u0440\u0438\u0439 \xab\u0421\u0430\u043b\u0430\u043c\u043f\u0438\xbb'), (b'nadegda', '\u0421\u0430\u043d\u0430\u0442\u043e\u0440\u0438\u0439 "\u041d\u0430\u0434\u0435\u0436\u0434\u0430"'), (b'nikolaeva', '\u0413\u043e\u0441\u0442\u0438\u043d\u0438\u0446\u0430 \u0410\u0423 "\u0426\u0435\u043d\u0442\u0440\u0430\u043b\u044c\u043d\u044b\u0439 \u0421\u0442\u0430\u0434\u0438\u043e\u043d \u0438\u043c. \u0410.\u0413. \u041d\u0438\u043a\u043e\u043b\u0430\u0435\u0432\u0430"'), (b'Chgpu', '\u0421\u0430\u043d\u0430\u0442\u043e\u0440\u0438\u0439 \u043f\u0440\u043e\u0444\u0438\u043b\u0430\u043a\u0442\u043e\u0440\u0438\u0439 \u0427\u0413\u041f\u0423 \u0438\u043c. \u0418.\u042f. \u042f\u043a\u043e\u0432\u043b\u0435\u0432\u0430 "\u041c\u0435\u0447\u0442\u0430"'), (b'Gemchugina', '\u041e\u0437\u0434\u043e\u0440\u043e\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0441 "\u0416\u0435\u043c\u0447\u0443\u0436\u0438\u043d\u0430 \u0427\u0443\u0432\u0430\u0448\u0438\u0438"')], max_length=30, verbose_name='\u041c\u0435\u0441\u0442\u043e \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u044f'),
        ),
    ]
