# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:59
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160324_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='file_music',
            field=models.FileField(blank=True, null=True, upload_to=app.models.make_upload_path_music, verbose_name='\u0410\u0443\u0434\u0438\u043e\u0437\u0430\u043f\u0438\u0441\u044c'),
        ),
    ]
