# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160324_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='member1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a N1'),
        ),
        migrations.AddField(
            model_name='participation',
            name='member2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a N1'),
        ),
        migrations.AddField(
            model_name='participation',
            name='member3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a N1'),
        ),
    ]
