# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160410_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='composition_1',
            field=models.CharField(max_length=200, verbose_name='\u041a\u043e\u043c\u043f\u043e\u0437\u0438\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='composition_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u041a\u043e\u043c\u043f\u043e\u0437\u0438\u0446\u0438\u044f \u21162'),
        ),
    ]
