# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160412_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
