# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160430_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='fest_num',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='member',
            name='fest_num',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='participation',
            name='fest_num',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='residing',
            name='fest_num',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='fest_num',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
