# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160615_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='fest_num',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
