# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20160629_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_residing_choices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
