# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20160629_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_residing_choices',
            name='db_name',
        ),
    ]
