# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_place_residing_choices_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='home_number',
            field=models.CharField(default='', max_length=200, verbose_name='\u0414\u043e\u043c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='region',
            field=models.CharField(default='empty', max_length=200, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='street',
            field=models.CharField(default=0, max_length=200, verbose_name='\u0423\u043b\u0438\u0446\u0430'),
            preserve_default=False,
        ),
    ]
