# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quantity_adult_female',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity_adult_male',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity_member_female',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity_member_male',
        ),
        migrations.AddField(
            model_name='food',
            name='quantity_adult',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u0437\u0440\u043e\u0441\u043b\u044b\u0445'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='quantity_member',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432'),
            preserve_default=False,
        ),
    ]
