# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20160720_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='obed_adult',
            field=models.BooleanField(default='false', verbose_name='\u041e\u0431\u0435\u0434'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='obed_member',
            field=models.BooleanField(default='false', verbose_name='\u041e\u0431\u0435\u0434'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='ugin_adult',
            field=models.BooleanField(default='false', verbose_name='\u0423\u0436\u0438\u043d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='ugin_member',
            field=models.BooleanField(default='false', verbose_name='\u0423\u0436\u0438\u043d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='zavtrak_adult',
            field=models.BooleanField(default='false', verbose_name='\u0417\u0430\u0432\u0442\u0440\u0430\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='zavtrak_member',
            field=models.BooleanField(default='false', verbose_name='\u0417\u0430\u0432\u0442\u0440\u0430\u043a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity_total',
            field=models.IntegerField(verbose_name='\u041e\u0431\u0449\u0435\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
