# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20160721_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041e\u0431\u0449\u0435\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
