# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20160721_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='obed_adult',
            new_name='obed',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='ugin_adult',
            new_name='ugin',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='zavtrak_adult',
            new_name='zavtrak',
        ),
        migrations.RemoveField(
            model_name='food',
            name='obed_member',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ugin_member',
        ),
        migrations.RemoveField(
            model_name='food',
            name='zavtrak_member',
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
