# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20160722_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place_arrival_choices',
        ),
    ]
