# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_delete_place_arrival_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('app_type', models.CharField(choices=[('participation', '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0443\u0447\u0430\u0441\u0442\u0438\u0435'), ('residing', '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u0435'), ('food', '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u043f\u0438\u0442\u0430\u043d\u0438\u0435'), ('transfer', '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u0442\u0440\u0430\u043d\u0441\u0444\u0435\u0440'), ('excursion', '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u044d\u043a\u0441\u043a\u0443\u0440\u0441\u0438\u0438')], max_length=50, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0437\u0430\u044f\u0432\u043e\u043a')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
