# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20160824_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Foto',
        ),
    ]
