# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xd0\x92\xd0\xb8\xd0\xb4\xd0\xb5\xd0\xbe'),
        ),
    ]
